sonar.projectKey=Airfluke_sonarqube
sonar.projectName=Airfluke_sonarqube
sonar.projectVersion=1.0
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000